apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: production
type: Opaque
stringData:
  database-url: 'postgresql://cloudops:cloudops123@postgres:5432/cloudops_db'
  openai-api-key: 'sk-test-key-replace-with-real-key'
  secret-key: 'your-32-character-secret-key-minimum-32-chars-long'y

